### ISSUE TITLE
Problem with double digit numbers in multiple select

### ISSUE THREAD

**Issue by systemshock89** [ghiscoding/multiple-select-vanilla#115]
Hi.
If there are two-digit numbers in multiple selects (example [ https://ghiscoding.github.io/multiple-select-vanilla/#/example03),]( https://ghiscoding.github.io/multiple-select-vanilla/#/example03) then when I select the value 15, the Select has the value 1, 5, 15 (but I only selected 15).

Please fix this bug

**Comment by ghiscoding** [comment]
it does not on my side 
![image](https://github.com/ghiscoding/multiple-select-vanilla/assets/643976/4bd416fa-b587-4533-9f3c-f6ee46e36530)

**Comment by systemshock89** [comment]
Sorry, maybe I'm not explaining it accurately, but

1. I select in "basic select" number 15.
![2023-08-17_16-40-03](https://github.com/ghiscoding/multiple-select-vanilla/assets/13196112/cbaa31f0-8ca6-4090-8c1d-640ffd8f78ca)

2. Then I check the value in this select with this function

`
function getSelectValues(select) {
  var result = [];
  var options = select && select.options;
  var opt;

  for (var i=0, iLen=options.length; i<iLen; i++) {
    opt = options[i];

    if (opt.selected) {
      result.push(opt.value || opt.text);
    }
  }
  return result;
}

 alert(getSelectValues(document.querySelector('select')));
`


3. I get the numbers 1, 5, 15 instead of the number 15 that I actually selected
![2023-08-17_16-41-06](https://github.com/ghiscoding/multiple-select-vanilla/assets/13196112/e9e84e1a-4eab-4b52-8d01-7174980dfc3b)

When using native multiple select everything works correctly - I get the number 15 if I select 15.
It does not work correctly when using this plugin

**Comment by ghiscoding** [comment]
Pull Request is welcome if you find how to fix it, but why don't you use `getSelects()` method instead? do you get the same result? I doubt it

[setSelects / getSelects](https://ghiscoding.github.io/multiple-select-vanilla/#/methods03)

Also note that I didn't create this library and I always use `getSelects` for my own usage

**Comment by systemshock89** [comment]
The `getSelects()` method gives the same result as my function.
In "Group Select" on the page [https://ghiscoding.github.io/multiple-select-vanilla/#/example03](https://ghiscoding.github.io/multiple-select-vanilla/#/example03), I selected a value of '11'.
Then using `multipleSelect('select')[1].getSelects() `I got ['1', '11'] instead of [11']

In the "Multiple Select with Jquery" plugin, it works correctly:
On the page [https://multiple-select.wenzhixin.net.cn/templates/template.html?v=701&url=multiple-items.html](https://multiple-select.wenzhixin.net.cn/templates/template.html?v=701&url=multiple-items.html) in "Group Select" I select 11 and using `$('select').multipleSelect('getSelects') `I get ['11']

I think the problem is in the "Multiple Select on js" plugin.
Ok, I'll use another plugin.

**Comment by ghiscoding** [comment]
It would be better if you could help to find the problem instead of just changing library

**Comment by ghiscoding** [comment]
found the problem to be that the comparison was done via a substring check instead of a full string value check. However please note that I was able to reproduce the error with the code you provided **but** I was **not** able to reproduce with the `.getSelects();` which is the method I always use which is probably why I did not catch the problem.

**Comment by systemshock89** [comment]
Thanks!
But now there is a new problem: I can't unckeckecked selected checkboxes in multipleSelect.
(unckeckecked values will be present in the array using the `.getSelects()` method)

In the "Multiple Select with Jquery" plugin, it works correctly.

**Comment by ghiscoding** [comment]
I pushed a new version, I found a regression bug after, you can test v0.4.9 instead

**Comment by systemshock89** [comment]
It works! Thank you very match!

**Comment by ghiscoding** [comment]
you can upvote the lib if it's helpful ⭐ 

bye now

**Comment by systemshock89** [comment]
I already voted. 
Bye
