### ISSUE TITLE
ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.

### ISSUE THREAD

**Issue by zkarpinski** [ghiscoding/multiple-select-vanilla#123]
Collecting page data ...Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules\multiple-select-vanilla\dist\cjs\multiple-select.js from node_modules\@slickgrid-universal\common\dist\commonjs\filters\selectFilter.js not supported.
multiple-select.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename multiple-select.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in node_modules\multiple-select-vanilla\package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

**Comment by ghiscoding** [comment]
I've removed the `type="module"` in the lib `package.json`, that should hopefully make it work with non-ESM import. 
Fix released in [v0.4.10](https://github.com/ghiscoding/multiple-select-vanilla/releases/tag/v0.4.10), give it a try
