### ISSUE TITLE
Encoding Values

### ISSUE THREAD

**Issue by hubpork** [ghiscoding/multiple-select-vanilla#170]
Hallo  ghiscoding, thanks for this plugin.
When value comes with "&" the plugin convert it to &amp;

Code
`<select name="categories" class="select-filter js-custom-filter-event" id="filter-categorie" multiple="multiple" placeholder="Bitte wählen" style="display: none;">
<option class="js-rubric-select-option" value="10">Ernährung & Hauswirtschaft</option>
</select>`
Output 
![grafik](https://github.com/ghiscoding/multiple-select-vanilla/assets/453997/3404d102-efa8-44a0-8cc5-9add3eaab685)

Do you have a solution? Or workaround?
Thank you

**Comment by ghiscoding** [comment]
Yeah that is normal since it won't render HTML by default unless you tell it to do that, you can use `textTemplate` and `renderOptionLabelAsHtml`, you can see the option in the [Live Demo - Text Template](https://ghiscoding.github.io/multiple-select-vanilla/#/options27)

**Comment by hubpork** [comment]
Thanks!
