### ISSUE TITLE
Support arrow navigation

### ISSUE THREAD

**Issue by morki** [ghiscoding/multiple-select-vanilla#206]
### Clear and concise description of the problem

Thank you for this awesome library. But one thing that makes it unusable for our use case is missing arrow navigation in opened popup.

### Suggested solution

It can be implemented.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ghiscoding** [comment]
That was already implemented in PR #176 which was first implemented in the original library in this [PR](https://github.com/wenzhixin/multiple-select/pull/613). As far as I can see, it is working fine.

**Comment by morki** [comment]
Oh, thank you for quick response. It "kinda" works, but:

- it is not possible navigate items when focus is in filter input
- popup is not focused automatically when there is no filter, so to use arrow navigation, one must "tab" into it

Both of those behaviours are unintuitive, that even me as developer didn't explore it.

**Comment by ghiscoding** [comment]
> * it is not possible navigate items when focus is in filter input

you just need to Tab out of the filter, I don't see a problem doing that. 

> Both of those behaviours are unintuitive, that even me as developer didn't explore it.

I would suggest you contribute a fix because I'm not expecting to work on this.
