### ISSUE TITLE
Option for placeholder to be always visible

### ISSUE THREAD

**Issue by Konrad-Afterlife-Olcha** [ghiscoding/multiple-select-vanilla#316]
### Clear and concise description of the problem

As a developer using Multiple-Select-Vanilla I suggest adding option, that will allow select placeholder to be always visible instead of selected values. Sometimes we want to display selected options in separate area, because of the UI requirements and leave select as-is, without selected values being visible. If I'm correct, that is not possible at the moment without some custom styling and coding on our side.

### Suggested solution

Adding option, that will allow placeholder being always visible, despite of selected values.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ghiscoding** [comment]
I'm going to have to close this issue unless more info is provided to explain the request

**Comment by ghiscoding** [comment]
closing since no feedback provided and I also think this should be implement in userland not here
